Lab11/blog/config/routes.rb
Blog::Application.routes.draw do
  resources :comments

  resources :articles

  root 'articles#index'

  

end

Lab11/blog/app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
end

Lab11/blog/app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :article

  def pretty_date
    created_at.strftime('%b %d, %Y at %I:%M %p')
  end

end

Lab11/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Lab11/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @comment = Comment.new(article_id: @article.id)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :content)
    end
end

Lab11/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        post_comment(@comment)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def post_comment(comment)
    require 'net/http'
    req = Net::HTTP::Post.new('/', initheader = {'Content-Type' => 'application/json'})
    req.body = comment.to_json(only: [ :id, :name, :content, :article_id ],
                               methods: :pretty_date)
    response = Net::HTTP.new('0.0.0.0', '3001').start {|http| http.request(req) }
    return
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:article_id, :name, :content)
    end
end

Lab11/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Lab11/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

Lab11/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

Lab11/blog/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Lab11/blog/app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<p>
  <%= link_to 'Show', @article %> |
  <%= link_to 'View all', articles_path %>
</p>

Lab11/blog/app/views/articles/index.html.erb
<h1>Articles</h1>

<div id="articles">
  <% for article in @articles %>
    <h2>
      <%= link_to article.name, article %>
      <span class="comments">
        (<%= pluralize(article.comments.size, 'comment') %>)
      </span>
    </h2>
    <div class="created_at">
      on <%= article.created_at.strftime('%b %d, %Y') %>
    </div>
    <div class="content">
      <%= simple_format truncate(article.content, length: 60, separator: ' ',
                   omission: '... (continued)') %>
    </div>
  <% end %>
</div>

<p><%= link_to "New Article", new_article_path %></p>

Lab11/blog/app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back to list', articles_path %>

Lab11/blog/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @article.name %></h2>

<div id="article" data-id="<%= @article.id %>">
  <%= simple_format @article.content %>
  
  <p><%= link_to 'Back to Articles', articles_path %></p>

  <% unless @article.comments.empty? %>
    <h3><%= pluralize(@article.comments.size, 'Comment') %></h3>
  <% end %>

  <div id="comments">
    <% unless @article.comments.empty? %>
      <%= render @article.comments %>
    <% end %>
    <% @article.comments.each do |comment| %>
        <div class="comment" data-time="<%= comment.created_at.to_i %>">
          <strong><%= comment.name %></strong>
          <em>on <%= comment.created_at.strftime('%b %d, %Y at %I:%M %p') %></em>
          <p><%= comment.content %></p>
        </div>
    <% end %>
  </div>

  <h3>Add a comment:</h3>

  <%= render partial: 'comments/form' %>

</div>