Lab4/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quotations

  root to: 'quotations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Lab4/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.member?
      can :read, Quotation
      can :create, Quotation
      can :update, Quotation do |quotation|
        quotation.try(:user) == user
      end
      can :destroy, Quotation do |quotation|
        quotation.try(:user) == user
      end
    else
      can :read, Quotation
    end
  end
end

Lab4/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Lab4/app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :user
end

Lab4/app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

Lab4/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  belongs_to :role
  has_many :quotation

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_validation :assign_role

  def assign_role
    self.role = Role.find_by_name('Member') if self.role.nil?
  end

  def admin?
    self.role.name == 'Admin' if !self.role.blank?
  end
  def member?
    self.role.name == 'Member' if !self.role.blank?
  end

end

Lab4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = 'Access denied.'
    redirect_to root_url
  end

end

Lab4/app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]
  #before_action :set_quotation, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # GET /quotations
  # GET /quotations.json
  def index
    #@quotations = Quotation.all
  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    #@quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations
  # POST /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)
    @quotation.user = current_user
    respond_to do |format|
      if @quotation.save
        format.html { redirect_to @quotation, notice: 'Quotation was successfully created.' }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    @quotation.user = current_user
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: 'Quotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url, notice: 'Quotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotation_params
      params.require(:quotation).permit(:quote)
    end

end

Lab4/app/helpers/application_helper.rb
module ApplicationHelper
end

Lab4/app/helpers/quotations_helper.rb
module QuotationsHelper
end

Lab4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <% if flash[:error] %>
        <div id="error">
          <%= flash[:error] %>
        </div>
      <% end %>
      <div id="container">
      <div id="user_status">
        <% if user_signed_in? %>
            Welcome
            <%= current_user.email %>! Not you?
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path %>
            or
            <%= link_to "Sign in", new_user_session_path %>.
        <% end %>
      </div>
      <br/>
      <%= yield %>
      </div>
  </body>
</html>

Lab4/app/views/quotations/_form.html.erb
<%= form_for(quotation) do |f| %>
  <% if quotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
      <% quotation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %>
    <%= f.text_field :quote %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Lab4/app/views/quotations/edit.html.erb
<h1>Editing Quotation</h1>

<%= render 'form', quotation: @quotation %>

<%= link_to 'Show', @quotation %> |
<%= link_to 'Back', quotations_path %>

Lab4/app/views/quotations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotations</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotations.each do |quotation| %>
      <tr>
        <td><%= quotation.quote %></td>
        <td><%= link_to 'Show', quotation %></td>
        <td><%= link_to 'Edit', edit_quotation_path(quotation) %></td>
        <td><%= link_to 'Destroy', quotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quotation', new_quotation_path %>

Lab4/app/views/quotations/new.html.erb
<h1>New Quotation</h1>

<%= render 'form', quotation: @quotation %>

<%= link_to 'Back', quotations_path %>

Lab4/app/views/quotations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @quotation.quote %>
</p>

<%= link_to 'Edit', edit_quotation_path(@quotation) %> |
<%= link_to 'Back', quotations_path %>